spring:
  redis:
    host: 192.168.111.133
    port: 6379
    database: 0
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 800ms
        max-idle: 8
        min-idle: 2
  cache:
    #缓存名称
    cache-names: test
    type: Caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  devtools:
    restart:
      enabled: true

server:
  port: 6900
