server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://ancient-poetry-eureka-server:9000/eureka/,http://ancient-poetry-eureka-server:9001/eureka/

spring:
  application:
    name: ancient-poetry-user-web


feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 2000