spring:
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    enabled: true
  redis:
    host: 192.168.111.133
    port: 6379
  devtools:
    restart:
      enabled: true
  application:
    name: ancient-poetry-web

server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://ancient-poetry-eureka-server:9000/eureka/

