spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ancient_article?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    enabled: true
  redis:
    host: 192.168.111.133
    port: 6379
  devtools:
    restart:
      enabled: true
  application:
    name: ancient-poetry-web

server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://ancient-poetry-eureka-server:9000/eureka/

feign:
  hystrix:
    enable: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 2500
  ConnectTimeout: 2500