server:
  port: 9021

eureka:
  client:
    serviceUrl:
      defaultZone: http://ancient-poetry-eureka-server:9000/eureka/


spring:
  application:
    name: ancient-poetry-user-core
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ancient_article?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    initial-size: 5
    min-idle: 5
    max-active: 50
    max-wait: 60000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    max-open-prepared-statements: 20
    validation-query: select 'x'
    pool-prepared-statements: true
    min-evictable-idle-time-millis: 300000
    time-between-eviction-runs-millis: 60000
  #Redis配置
  redis:
    host: 192.168.232.131
    port: 6379
    database: 0
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 800ms
        max-idle: 8
        min-idle: 2
  cache:
    #缓存名称
    cache-names: test
    type: Caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

mybatis:
  type-aliases-package: com.moon.ancientpoetry.common.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
