server:
  port: 7101

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ancient_article?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #Redis配置
  redis:
    host: 192.168.111.133
    port: 6379
    database: 0
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 800ms
        max-idle: 8
        min-idle: 2
  cache:
    #缓存名称
    cache-names: test
    type: Caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

mybatis:
  type-aliases-package: com.moon.ancientpoetry.common.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
